### ISSUE TITLE
DigitalRead on the OUTPUT pins are not working.

### ISSUE THREAD

**Issue by zekageri** [xreef/PCF8574_library#20]
If i perform a digitalRead(PIN) on a PIN that is defined OUTPUT, it always returns 0. Doesn't matter if the PIN is on HIGH or LOW.

**Comment by xreef** [comment]
Hi zekageri,
the pins works like the microcontrollers pins.
So to read the pin must be in Input.
Bye Renzo

**Comment by zekageri** [comment]
So how can i determine if the pin is actually high?

**Comment by xreef** [comment]
Hi, 
to get the input value pin must be INPUT.
Bye Renzo

**Comment by alirezaimi** [comment]
Hi
In nodemcu that i tested and i can read the output pin of relay whenever i want in OUTPUT state !
what do you mean ?
The output is always shown return low !this is wrong !
