### ISSUE TITLE
Buzzing motor usign L298n

### ISSUE THREAD

**Issue by Powablocks** [xreef/PCF8574_library#21]
Hello,
I'm currently trying to use your library for my project but when data are read from the expander board a buzzing sound come from one of the motor connected to eh L298n.
I'm using a NodeMCU V3, two L298n connected through D1 to D8 and a PCF8574 board connected on Rx and Tx (because it was added after the motors). 
The issue only occurs when the PCF8574 is used (Read or Write).
Do you think the issue come from me or others things ?
Could it be because the real I2C pins are connected to the inputs of the L298N ?
Thanks for reading and wish you can help me.
Powablocks

**Comment by xreef** [comment]
Hi Powablocks,
sorry for the late reply, to understand you must give us an example sketch, I have to few information to help you.
Bye Renzo
