### ISSUE TITLE
Incorrect address?

### ISSUE THREAD

**Issue by QuitButton** [xreef/PCF8574_library#37]
The example encoderWithBasicLibraryFunction.ino has the following:
`// initialize library
PCF8574 pcf8574(0x38, INTERRUPTED_PIN, updateEncoder);`

What is the 0x38 value? I can't see how the PCF8574 can be set to that address.

**Comment by xreef** [comment]
Hi QuitButton,
The first value it's the address, but you can check all information in the guide.

https://www.mischianti.org/2019/01/02/pcf8574-i2c-digital-i-o-expander-fast-easy-usage/

Bye Renzo
