### ISSUE TITLE
use tm1637 with pcf8574 port expander

### ISSUE THREAD

**Issue by alirezaimi** [xreef/PCF8574_library#43]
Hi
How can i use tm1637 7segment with pcf8574 port expander ?

PCF8574 expander(0x20, 4, 5); // esp8266 nodemcu and all Ax pins are Grounded
TM1637Display display(P4, P5);

and when i connect pins to 4 and 5 of esp8266 board its work !

**Comment by xreef** [comment]
Hi alirezaimi,
I don't know very well that display, but I think no.
Bye Renzo

**Comment by alirezaimi** [comment]
hi again
And There is no way that you can add it to this project or way to work with ?!!! So fast to close  an issue!!!
I want to work with some i2c port with pcf module! Is there any way in this lib?! Or if is not, is there any way to add it ???

Thanks.
