### ISSUE TITLE
if (pcf8574.begin()) is always ko !!!

### ISSUE THREAD

**Issue by Deltaplc** [xreef/PCF8574_library#53]
Good morning
Everything works fine with this library .... there is only one problem the pcf8574.begin () function has always been "KO" answer even if it sees the pcf8574 and everything works!
Can you give me some help? that function would serve me to monitor the functioning of the i2c communication.
Greetings
David

**Comment by xreef** [comment]
Hi @Deltaplc,
not all microcontroller core support feedback on endTransmission sorry i can't do nothing.
Bye Renzo
