### ISSUE TITLE
digitalWrite(PIN, LOW) changes all pins to LOW

### ISSUE THREAD

**Issue by rozrabiak** [xreef/PCF8574_library#54]
Below code changes all input pins to LOW. Arduino NANO, PCF8574 WaveShare. I'm using: #define PCF8574_LOW_MEMORY
And one more question, why in examples pcf.begin() is below pin mode definition in setup? It doesn't work properly, pin mode not change when pcf.begin() is below pin definition. Tested on Arduino NANO and PCF8574 WaveShare,

#include <Arduino.h>
#include <PCF8574.h>

#define intPin 2
void intBtnVoid();
bool keyPressed = false;
PCF8574 pcf(0x22, intPin, intBtnVoid);

void setup() {
  // put your setup code here, to run once:
  pcf.begin();
  pcf.pinMode(P0, INPUT);
  pcf.digitalWrite(P0, LOW);	// <- change ALL INPUT pins to LOW
  pcf.pinMode(P1, INPUT);
  pcf.pinMode(P2, INPUT);
  pcf.pinMode(P3, INPUT);
  pcf.pinMode(P4, INPUT);
}

void loop() {
  if(keyPressed)
  {
		//some code	
  }
}

void intBtnVoid(){
  keyPressed = true;
}

**Comment by xreef** [comment]
Hi @rozrabiak,
yes the sketch is wrong, you must define the pin mode before the begin.
And a digital write on an input PIN isn't a good practice.
Bye Renzo
