### ISSUE TITLE
class PCF8574' has no member named 'pinMode'

### ISSUE THREAD

**Issue by OslafEman** [xreef/PCF8574_library#59]
Hi, I got this error message (**class PCF8574' has no member named 'pinMode'**) every time I try to use any example from the library.  I´m using an MH ET LIVE ESP32Mini Kit processor with Arduine IDE version 1.8.19 and Windows 11.

Oslaf

**Comment by xreef** [comment]
Check if the active library is the current
 PCF8574_library
sometime, if you have multiple libraries installed the IDE get the wrong one.
Bye Renzo

**Comment by OslafEman** [comment]
Thanks a lot Renzo, it works now.  Great job!

Oslaf

**Comment by xreef** [comment]
Perfect! If you need more help you can use the forum also 
https://www.mischianti.org/forums/forum/mischiantis-libraries/
I am more present there, sometimes I lose the issues on github.
Bye Renzo
