### ISSUE TITLE
digitalWrite cause toggle on another pin

### ISSUE THREAD

**Issue by taufikterdidik** [xreef/PCF8574_library#6]
...
PCF8574 ioexp(0x3F, PIN_WIRE_SDA, PIN_WIRE_SCL);
...
void setup(){
  ioexp.pinMode(P0, OUTPUT);
  ioexp.pinMode(P1, OUTPUT);
  ioexp.pinMode(P2, OUTPUT);
  ioexp.pinMode(P3, OUTPUT);
  ioexp.pinMode(P4, OUTPUT);
  ioexp.pinMode(P5, OUTPUT);
  ioexp.pinMode(P6, OUTPUT);
  ioexp.pinMode(P7, OUTPUT);
  ioexp.begin();
  ...
}

void loop(){
   ...
  ioexp.digitalWrite(P0, HIGH);
  //other pin will all LOW
  ....
  ioexp.digitalWrite(P1, HIGH);
  //other pin (include P0) change to LOW
....
}

How to set only 1 pin, and another pin not toggling

**Comment by xreef** [comment]
Hi I replicate your test, but when I set the second pin P1, P0 remain HIGH as It is.
Can you explain better PLZ.
Thanks
