### ISSUE TITLE
Using Arduino_STM32 Core

### ISSUE THREAD

**Issue by nopnop2002** [xreef/PCF8574_library#8]
I tried with Arduino_STM32 Core.

I made alterations a little.

PCF8574.h

private:
	uint8_t _address;
//	uint8_t _sda = SDA;
//	uint8_t _scl = SCL;
	uint8_t _sda;
	uint8_t _scl;

PCF8574.cpp

void PCF8574::begin(){
	#ifndef __AVR
		#if defined(__STM32F1__)
			Wire.begin();
		#else
			Wire.begin(_sda, _scl);
		#endif
	#else
	//			Default pin for AVR some problem on software emulation
	//			#define SCL_PIN _scl
	// 			#define SDA_PIN _sda
		Wire.begin();
	#endif
 

Thank you for useful library.

**Comment by xreef** [comment]
Please give me a feedback about integration of SMT32. 
Thanks

**Comment by xreef** [comment]
I hope this fix..

**Comment by xreef** [comment]
Thanks for your support and your patience. 
Bye
