### ISSUE TITLE
using on esp32 doit Devkit V1

### ISSUE THREAD

**Issue by rebe0909** [xreef/PCF8574_library#9]
Hello.
I'am trying to use your lib on a esp32 devkit.
It does compile but I can't see the right values of the Inputs.
I have 4 pcs of PCF8574AN connected to the bus and get the Adresses 0x38, 0x39, 0x3A and 0x3B when I try to scan the bus for devices.

Could you imagine what's the problem is?
thanks & kind regards

**Comment by xreef** [comment]
Hi,
try to decomment this line and take a look to the serial output.

// #define PCF8574_DEBUG

Check if you get some information.
Bye

**Comment by rebe0909** [comment]
Hi.
I did what you suggestet, but the output given did not help:
Read pin 0
Read from buffer
Data ready
Buffer value 0
Return value 0
Read pin 1
Buffer value 0
Return value 0
Read pin 2

In your lib in the .h file I tried to add a declaration of:
TwoWire wire = TwoWire(0);
because this seems to work (testet without your lib) with esp32 (esp32 has 2 I2C )
At wire.begin I added: 		Wire.begin(_sda, _scl, 10000);
Because the TwoWire needs the frequency as Param.

BUT: No success :-(

**Comment by xreef** [comment]
I don't have an esp32 so I look around and I find this:
#define SDA_PIN 21
#define SCL_PIN 22

pinMode(SDA_PIN,INPUT_PULLUP);
pinMode(SCL_PIN,INPUT_PULLUP);

Wire.begin(SDA_PIN, SCL_PIN); // 21 & 22 are default on ESP32

try to add 10k pull-ups on SDA and SCL lines.

**Comment by xreef** [comment]
Close for inactivity
